name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install buildozer kivy

      - name: Build iOS app
        run: |
          buildozer init || true
          buildozer -v ios debug

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: bin/*.ipa
