name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Homebrew system packages
        run: |
          brew install autoconf automake libtool pkg-config gmp mpfr libmpc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade cython
          pip install buildozer kivy pbxproj packaging

      - name: Initialize buildozer if needed
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build iOS app
        run: |
          buildozer -v ios debug

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: bin/*.ipa
